import assert from 'node:assert/strict';
import {normalize,fromEuler,slerp,quaternionMatrix,multiply,WORLD_TO_VIEW} from '../components/drone_web/web/math.js';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
const transform=(m,v)=>[0,1,2].map(r=>m[r]*v[0]+m[4+r]*v[1]+m[8+r]*v[2]);
const vector=(a,b)=>a.forEach((v,i)=>near(v,b[i]));
assert.equal(normalize([0,0,0,0]),null);
assert.equal(normalize([NaN,0,0,0]),null);
assert.equal(normalize([1,0,0]),null);
vector(normalize([2,0,0,0]),[1,0,0,0]);
vector(transform(quaternionMatrix(fromEuler(0,0,Math.PI/2)),[1,0,0]),[0,1,0]);
vector(transform(quaternionMatrix(fromEuler(Math.PI/2,0,0)),[0,1,0]),[0,0,1]);
vector(transform(quaternionMatrix(fromEuler(0,Math.PI/2,0)),[1,0,0]),[0,0,-1]);
vector(transform(WORLD_TO_VIEW,[0,0,1]),[0,1,0]);
vector(transform(WORLD_TO_VIEW,[0,1,0]),[0,0,-1]);
vector(transform(multiply(WORLD_TO_VIEW,quaternionMatrix(fromEuler(0,0,Math.PI/2))),[1,0,0]),[0,0,-1]);
vector(slerp([1,0,0,0],[-1,0,0,0],.5),[1,0,0,0]);
const halfway=slerp([1,0,0,0],fromEuler(0,0,Math.PI/2),.5);
vector(transform(quaternionMatrix(halfway),[1,0,0]),[Math.SQRT1_2,Math.SQRT1_2,0]);
near(Math.hypot(...slerp(fromEuler(.4,.8,.9),fromEuler(-.3,-.7,.6),.3)),1);
console.log('PASS: quaternion rotations, body/world/view axes, normalization, shortest-path interpolation');
